### ISSUE TITLE
GIL is not released in `openravepy.planningutils`.

### ISSUE THREAD

**Issue by psigen** [personalrobotics/openrave#4]
The python bindings for `openravepy.planningutils` do not release the Python GIL, meaning that they completely block Python thread execution as long as they are running.

This is particularly bad in the case of long-running operations such as path retiming/smoothing, which can easily take 0.25 to 0.5 seconds.

The following lines are definitely places where one would want to release the GIL:
https://github.com/rdiankov/openrave/blob/master/python/bindings/openravepy_planningutils.cpp#L97
https://github.com/rdiankov/openrave/blob/master/python/bindings/openravepy_planningutils.cpp#L102
https://github.com/rdiankov/openrave/blob/master/python/bindings/openravepy_planningutils.cpp#L107

**Comment by mkoval** [comment]
I don't think we want to release the GIL unconditionally. All of the default OpenRAVE code defaults to leaving the GIL locked unless you pass an explicit `releasegil` flag. It makes sense to duplicate that behavior here.

If anyone needs a quick workaround: you can instantiate and call the smoother manually. The `RetimeTrajectory` functions are just shorthand for doing this in one function call.

**Comment by psigen** [comment]
This was fixed in #5.
